server:
  port: 8888

# 应用名称
spring:
  application:
    name: GuKing
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis
  redis:
    host: localhost
    port: 6379

# 上传文件配置
  servlet:
    multipart:
      # 上传文件最大值
      max-request-size: 20MB
      # 单个文件最大值
      max-file-size: 2MB
mybatis-plus:
  configuration:
    # sql打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 数据库表名的前缀
      table-prefix: ms_
  mapper-locations: classpath:mapper/*.xml


qiniu:
  accessKey: AEnNUNnO3_z-3DkgyvixmboSFTUcc2t4YyYzg9ai
  accessSecretKey: -7GoFubdJDJ_xLtea9zClhi9sXwUbEEeHl5jEyZC



